import React from "react";
import { connect } from "react-redux";
import { injectIntl } from "react-intl";

import { Paper, Grid, Typography, Divider } from "@mui/material";
import { styled } from "@mui/material/styles";

import {
  decodeId,
  formatDateFromISO,
  formatMessage,
  historyPush,
  withHistory,
  withModulesManager,
  ProgressOrError,
  Table,
  GRID_RESPONSIVE_FULL,
} from "@openimis/fe-core";

import InvoiceStatusPicker from "../pickers/InvoiceStatusPicker";
import { useInvoiceLineItemsByLine } from "../hooks";
import { RIGHT_INVOICE_SEARCH, EMPTY_STRING } from "../constants";

const StyledPaper = styled(Paper)(({ theme }) => ({
  ...(theme?.paper?.paper ?? {}),
  "& .paperHeader": theme?.paper?.header ?? {},
  "& .tableTitle": theme?.table?.title ?? {},
}));

/**
 * Read-only panel contributed to `policy.Policy.panels`: the invoices raised for
 * the policy on screen. Invoices are generated by the backend calculation rules,
 * so no creation action is offered.
 */
const PolicyInvoicesPanel = ({ intl, modulesManager, history, edited, rights }) => {
  // the invoice line item's generic FK stores the policy's integer pk
  const lineId = edited?.id ? String(decodeId(edited.id)) : null;
  const canSearch = rights?.includes(RIGHT_INVOICE_SEARCH);

  const { isLoading, error, lineItems } = useInvoiceLineItemsByLine(lineId, { skip: !lineId || !canSearch });

  if (!lineId || !canSearch) return null;

  // the query returns relay global ids, while the invoice route resolves a raw uuid
  const openInvoice = (item, newTab = false) =>
    !!item?.invoice?.id &&
    historyPush(modulesManager, history, "invoice.route.invoice", [decodeId(item.invoice.id)], newTab);

  const headers = [
    "invoice.code",
    "invoice.dateInvoice",
    "invoice.dateDue",
    "invoice.amountTotal",
    "invoice.status.label",
  ];

  const itemFormatters = [
    (item) => item.invoice?.code ?? EMPTY_STRING,
    (item) =>
      item.invoice?.dateInvoice
        ? formatDateFromISO(modulesManager, intl, item.invoice.dateInvoice)
        : EMPTY_STRING,
    (item) =>
      item.invoice?.dateDue ? formatDateFromISO(modulesManager, intl, item.invoice.dateDue) : EMPTY_STRING,
    (item) => item.invoice?.amountTotal ?? item.amountTotal ?? EMPTY_STRING,
    (item) => <InvoiceStatusPicker value={item.invoice?.status} readOnly />,
  ];

  return (
    <Grid size={GRID_RESPONSIVE_FULL}>
      <StyledPaper>
        <Grid container alignItems="center" direction="row" className="paperHeader">
          <Grid size={12}>
            <Typography className="tableTitle">
              {formatMessage(intl, "invoice", "policyInvoices.title")}
            </Typography>
          </Grid>
        </Grid>
        <Divider />
        <ProgressOrError progress={isLoading} error={error} />
        {!isLoading && !error && (
          <Table
            module="invoice"
            headers={headers}
            itemFormatters={itemFormatters}
            items={lineItems}
            onDoubleClick={openInvoice}
          />
        )}
      </StyledPaper>
    </Grid>
  );
};

const mapStateToProps = (state) => ({
  rights: !!state.core && !!state.core.user && !!state.core.user.i_user ? state.core.user.i_user.rights : [],
});

export { PolicyInvoicesPanel };

export default withModulesManager(withHistory(injectIntl(connect(mapStateToProps)(PolicyInvoicesPanel))));
